apiVersion: v1
kind: Secret
metadata:
  name: cb-secret
type: Opaque
data:
  username: QWRtaW5pc3RyYXRvcg==  # Administrator
  password: cGFzc3dvcmQ=          # password
---
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-cluster
  labels:
    repoUserOrg: steve
    repoName: cluster-1
spec:
  image: couchbase/server:6.6.0
  security:
    adminSecret: cb-secret
  networking:
    exposeAdminConsole: true
    adminConsoleServices:
    - data
  buckets:
    managed: false
  servers:
  - size: 1
    name: cb-servers-1
    services:
    - data
    - index
    - query
    - search
