apiVersion: v1
kind: Secret
metadata:
  name: cbConfigPathSafe-secret
type: Opaque
data:
  username: QWRtaW5pc3RyYXRvcg==  # Administrator
  password: cGFzc3dvcmQ=          # password
---
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cbConfigPathSafe
  annotations:
    repoPath: "cbConfigPath"
    repoPathSHA: "cbConfigPathSHA"
spec:
  image: couchbase/server:6.6.0
  security:
    adminSecret: cbConfigPathSafe-secret
  networking:
    exposeAdminConsole: true
    adminConsoleServices:
    - data
  buckets:
    managed: false
  servers:
  - size: 1
    name: cbConfigPathSafe-servers-1
    services:
    - data
    - index
    - query
    - search
